name: Update All Standings

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Heren1:
    uses: ./.github/workflows/Heren1.yml
  Heren2:
    uses: ./.github/workflows/Heren2.yml
  Heren3:
    uses: ./.github/workflows/Heren3.yml
  Dames1:
    uses: ./.github/workflows/Dames1.yml
  Dames2:
    uses: ./.github/workflows/Dames2.yml
  U18:
    uses: ./.github/workflows/U18.yml
  U18VHV:
    uses: ./.github/workflows/U18VHV.yml
  U16:
    uses: ./.github/workflows/U16.yml
  U16VHV:
    uses: ./.github/workflows/U16VHV.yml
  U14:
    uses: ./.github/workflows/U14.yml
  U14VHV:
    uses: ./.github/workflows/U14VHV.yml
  M14:
    uses: ./.github/workflows/M14.yml
  M14VHV:
    uses: ./.github/workflows/M14VHV.yml
  U12:
    uses: ./.github/workflows/U12.yml
