# .github/workflows/Heren1.yml

name: Update Standings Heren1

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}  # laat je ook manueel triggeren via de GitHub UI

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 18702
      NAME: Heren1
