name: Update Standings Heren2

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 18702
      NAME: Heren2
