name: Update Standings Heren1

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # laat je ook manueel triggeren via de GitHub UI

permissions:
  contents: write

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 18702
      NAME: Heren1
