name: Update Standings M14VHVQual

on:
  workflow_dispatch:
  workflow_call: 

permissions:
  contents: write

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 19562
      NAME: M14VHVQual
