name: Update Standings M14VHV

on:
  workflow_dispatch:
  workflow_call: 

permissions:
  contents: write

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 18728
      NAME: M14VHV
