name: Test Scheduler

on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch: {}  # laat je ook manueel triggeren via de GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduler works"
