name: Update Standings U12

on:
  workflow_dispatch:
  workflow_call: 

permissions:
  contents: write

jobs:
  call-workflow:
    uses: ./.github/workflows/update-standings.yml
    with:
      LEAGUE: 18731
      NAME: U12
